plugins {
    id 'java'
    id 'org.springframework.boot' version '3.4.0'
    id 'io.spring.dependency-management' version '1.1.7'
    id 'jacoco'
}


group = 'com.sprint.mission'
version = '1.0-SNAPSHOT'


java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

repositories {
    mavenCentral()
}

dependencies {

    // AOP
    implementation 'org.springframework.boot:spring-boot-starter-aop'

    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.7.0'
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'
    implementation 'org.springframework.boot:spring-boot-starter-thymeleaf'
    // 벨리데이션
    implementation 'org.springframework.boot:spring-boot-starter-validation'

    // actuator (애플리케이션의 내부 상태, 헬스 체크, 메트릭 등을 모니터링)
    implementation 'org.springframework.boot:spring-boot-starter-actuator'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testCompileOnly 'org.projectlombok:lombok'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    testAnnotationProcessor 'org.projectlombok:lombok'

    // mapstruct(Lombook보다 뒤에있어야한다고함)
    implementation 'org.mapstruct:mapstruct:1.5.3.Final'
    annotationProcessor 'org.mapstruct:mapstruct-processor:1.5.3.Final'

    // admin
    implementation 'de.codecentric:spring-boot-admin-starter-client:3.2.3'

    runtimeOnly 'org.postgresql:postgresql'
    runtimeOnly 'com.h2database:h2'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'


}

tasks.named('test') {
    useJUnitPlatform()
    finalizedBy 'jacocoTestReport' // 테스트 후에 JaCoCo 리포트 생성
}

// Jacoco 관련 설정
jacoco {
    toolVersion = "0.8.11"  // 버전에 맞는 jacoco 설정
}

// 리포트 생성
jacocoTestReport {
    dependsOn test
    reports {
        xml.required = true
        html.required = true
    }
    // 서비스만 보기위해서 필터링
//    classDirectories.setFrom(files(classDirectories.files.collect {
//        fileTree(dir: it, include: [
//                'com/sprint/mission/discodeit/service/user/**',
//                'com/sprint/mission/discodeit/service/channel/**',
//                'com/sprint/mission/discodeit/service/message/**'
//        ])
//    }))
    classDirectories.setFrom(files(classDirectories.files.collect {
        fileTree(dir: it, include: ['com/sprint/mission/discodeit/service/**'])
    }))
}

// violationRules에 따라서 커버리지를 만족하는지 검증
jacocoTestCoverageVerification {
    // 검사 대상을 service 패키지로만 한정
    classDirectories.setFrom(files(classDirectories.files.collect {
        fileTree(dir: it, include: ['com/sprint/mission/discodeit/service/**'])
    }))

    violationRules {
        rule {
            element = 'BUNDLE'          // 클래스별이 아니라 대상 전체 합계로 계산
            limit {
                counter = 'LINE'        // 코드 줄 기준
                value = 'COVEREDRATIO'  // 실행된 비율
                minimum = 0.60          // 60% 이상
            }
        }
    }
}
