services:
  postgres-db:
    image: postgres:15
    container_name: discodeit-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: discodeit_user
      POSTGRES_PASSWORD: discodeit1234
      POSTGRES_DB: discodeit
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: