input {
  file {
    path => "/var/log/app/app*.log"
    start_position => "beginning"
    sincedb_path => "/dev/null"
    codec => multiline {
      pattern => "^\d{4}-\d{2}-\d{2}"
      negate => "true"
      what => "previous"
    }
  }
}

filter {
  grok {
    match => {
      "message" => "%{TIMESTAMP_ISO8601:log_time}\s+\[%{DATA:thread}\]\s+%{LOGLEVEL:log_level}\s+%{NOTSPACE:logger}\s+\[%{DATA:client_ip}\]\s+\[%{DATA:user_id}\]\s+-\s+%{GREEDYDATA:log_message}"
    }
  }
  date {
    match => ["log_time", "yyyy-MM-dd HH:mm:ss.SSS"]
    timezone => "Asia/Seoul"
    target => "@timestamp"
  }
  mutate{
    gsub => ["log_message", "\r", ""]
  }
  mutate {
    remove_field => [ "event", "host", "@version", "message", "log" ]
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "spring-logs-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug }
}