discodeit:
  seed: true
  repository:
    type: file   # jcf | file
    file-directory: .discodeit

spring:
  application:
    name: Discodeit
  servlet:
    encoding:
      charset: UTF-8
      force: true

springdoc:
  swagger-ui:
    tags-sorter: alpha          # Controller 알파벳 정렬
    operations-sorter: alpha    # URL 알파벳 정렬

server:
  port: 8080
